apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: receipt-ocr-api
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - receipt-ocr

  selector:
    matchLabels:
      app: receipt-ocr-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s